const express = require("express");
const router = express.Router();
const { getAllOrderAddresses, getOrderAddressById, getAddressesByOrderId, createOrderAddress, updateOrderAddress, deleteOrderAddress } = require("../controllers/orderAddress.controller");
router.get("/", getAllOrderAddresses);
router.get("/order/:order_id", getAddressesByOrderId);
router.get("/:id", getOrderAddressById);
router.post("/", createOrderAddress);
router.put("/:id", updateOrderAddress);
router.delete("/:id", deleteOrderAddress);
module.exports = router;
