/**
 * datareview.js
 * Kanila Beauty Commerce - seed 10 positive reviews (4-5 stars) for every product.
 *
 * Designed to run after:
 *   1) dataproduct_copy.js
 *   2) dataremaining.js
 *
 * The script reads the existing products, product variants and customers, then creates:
 * - 1 completed mock order for each review
 * - 1 matching order item for each review
 * - 1 order total, order address and completed status history for each order
 * - 10 visible, verified-purchase reviews for every product
 * - review_summary/review_summaries aggregates synchronized from visible reviews
 *
 * Review documents use the current Review schema exactly:
 *   customer_id, orderItemId, productId, variantId, rating,
 *   reviewTitle, reviewContent, reviewStatus, helpfulCount,
 *   verifiedPurchaseFlag, createdAt, updatedAt, __v
 *
 * Usage from backend root:
 *   npm install dotenv mongoose
 *   node datareview.js
 *
 * Optional:
 *   node datareview.js --reset
 *     Deletes only deterministic rows generated by this script, then inserts them again.
 *
 *   REVIEWS_PER_PRODUCT=10 node datareview.js
 *     Changes the number of reviews generated for each product.
 *
 * Requirements:
 *   .env must contain one of: MONGODB_URI, MONGO_URI, MONGODB_URL, DATABASE_URL
 */

'use strict';

require('dotenv').config();
const crypto = require('crypto');
const mongoose = require('mongoose');

const { ObjectId } = mongoose.Types;

const SEED_NAMESPACE = 'kanila_product_reviews_v1';
const REVIEWS_PER_PRODUCT = Math.max(
  1,
  Number.parseInt(process.env.REVIEWS_PER_PRODUCT || '10', 10) || 10,
);
const SHOULD_RESET = process.argv.includes('--reset');

const COLLECTION = {
  products: 'products',
  variants: 'product_variants',
  customers: 'customer_profiles',
  customerAddresses: 'customer_addresses',
  orders: 'orders',
  orderItems: 'order_items',
  orderTotals: 'order_totals',
  orderAddresses: 'order_addresses',
  orderStatusHistory: 'order_status_history',
  reviews: 'reviews',
};

const RATING_PATTERN = [5, 5, 5, 5, 5, 5, 5, 4, 4, 4];

const GENERIC_TITLES = [
  'Rất hài lòng với sản phẩm',
  'Chất lượng tốt, dễ sử dụng',
  'Đúng như mô tả',
  'Dùng hằng ngày rất ổn',
  'Sẽ tiếp tục mua lại',
  'Trải nghiệm tốt hơn mong đợi',
  'Đóng gói kỹ, sản phẩm đẹp',
  'Phù hợp với nhu cầu của mình',
  'Hiệu quả và tiện dùng',
  'Một lựa chọn đáng thử',
];

const SKIN_CONTEXTS = [
  'da dầu',
  'da khô',
  'da hỗn hợp',
  'da thường',
  'da nhạy cảm nhẹ',
];

const USAGE_CONTEXTS = [
  'dùng buổi sáng',
  'dùng trong routine buổi tối',
  'mang theo khi đi làm',
  'dùng khi trang điểm hằng ngày',
  'dùng trong thời tiết nóng ẩm',
  'dùng liên tục hơn một tuần',
  'dùng khi cần makeup nhanh',
  'dùng trước khi ra ngoài',
  'dùng xen kẽ trong routine',
  'dùng khi đi du lịch',
];

const REVIEW_LIBRARY = {
  cleanser: [
    ['Làm sạch tốt mà không căng da', 'Khả năng làm sạch ổn, bọt vừa phải và sau khi rửa da vẫn mềm.'],
    ['Dịu nhẹ, dễ dùng mỗi ngày', 'Mình dùng sáng và tối đều ổn, da không bị khô rít hay khó chịu.'],
    ['Da sạch thoáng hơn', 'Sản phẩm làm sạch dầu thừa tốt nhưng không tạo cảm giác bị lấy hết độ ẩm.'],
    ['Hợp với routine tối giản', 'Kết cấu dễ rửa, không để lại màng nhờn và dùng cùng các bước dưỡng rất thuận tiện.'],
    ['Rửa mặt xong vẫn ẩm', 'Điểm mình thích nhất là da sạch nhưng vẫn giữ được cảm giác mềm và dễ chịu.'],
    ['Dùng trong thời tiết nóng rất ổn', 'Sau một ngày dài sản phẩm làm sạch khá tốt, vùng chữ T thoáng hơn.'],
    ['Không gây châm chích', 'Da mình khá nhạy cảm nhưng dùng sản phẩm này không thấy rát hay đỏ bất thường.'],
    ['Kết cấu dễ tạo bọt', 'Chỉ cần lượng nhỏ đã đủ dùng, massage dễ và rửa lại nhanh.'],
    ['Mùi nhẹ, cảm giác sạch sẽ', 'Mùi không quá nồng, sau khi dùng da sạch và không bị bí.'],
    ['Đáng mua lại', 'Hiệu quả làm sạch cân bằng, phù hợp để dùng lâu dài trong routine hằng ngày.'],
  ],
  micellar: [
    ['Tẩy sạch nhanh và dịu', 'Lớp kem chống nắng và makeup nhẹ được làm sạch khá nhanh, da không bị rát.'],
    ['Không để lại cảm giác nhờn', 'Sau khi lau da khá thoáng và không có lớp màng khó chịu.'],
    ['Hợp với da nhạy cảm', 'Vùng mắt và môi dùng nhẹ tay vẫn ổn, không gây châm chích nhiều.'],
    ['Tiện cho những hôm makeup nhẹ', 'Chỉ cần vài miếng bông là làm sạch được lớp nền hằng ngày.'],
    ['Làm sạch ổn, không khô da', 'Sau bước tẩy trang da vẫn mềm, không bị căng rít.'],
    ['Dễ dùng mỗi tối', 'Kết cấu nước nhẹ, không mùi nồng và thao tác rất nhanh.'],
    ['Tẩy son khá tốt', 'Son và lớp base được lấy đi tương đối sạch mà không cần chà mạnh.'],
    ['Da sạch nhưng vẫn dễ chịu', 'Sản phẩm cân bằng tốt giữa khả năng làm sạch và độ dịu nhẹ.'],
    ['Phù hợp mang đi du lịch', 'Dùng tiện, làm sạch nhanh và không cần nhiều bước phức tạp.'],
    ['Mình sẽ mua lại', 'Hiệu quả ổn định, dùng hằng ngày không gây bí hay khó chịu.'],
  ],
  sunscreen: [
    ['Thấm nhanh, không quá bết', 'Chất kem tán dễ và ráo tương đối nhanh, dùng dưới makeup khá ổn.'],
    ['Không để lại vệt trắng rõ', 'Khi tán kỹ sản phẩm tiệp da tốt, không bị loang hay vón.'],
    ['Dùng hằng ngày rất tiện', 'Kết cấu nhẹ, dễ thoa đủ lượng và không làm da nặng mặt.'],
    ['Lớp finish đẹp', 'Da trông tự nhiên hơn, không bóng dầu quá mức trong vài giờ đầu.'],
    ['Không cay mắt nhiều', 'Mình thoa gần vùng mắt vẫn tương đối dễ chịu và không bị chảy nước mắt.'],
    ['Hợp thời tiết nóng ẩm', 'Sản phẩm bám ổn, không bị trượt nền nhanh khi ra ngoài.'],
    ['Dễ kết hợp với makeup', 'Kem nền phủ lên khá mượt, không bị vón ở những vùng khô.'],
    ['Không gây bí da', 'Dùng liên tục mình chưa thấy nổi mụn bất thường hay cảm giác ngột ngạt.'],
    ['Bảo vệ da tốt cho nhu cầu hằng ngày', 'Phù hợp đi làm và di chuyển ngoài trời trong thời gian vừa phải.'],
    ['Sẽ mua lại', 'Trải nghiệm tổng thể tốt, dễ dùng và phù hợp routine buổi sáng.'],
  ],
  serum: [
    ['Thấm nhanh và không bết', 'Kết cấu mỏng, tán dễ và dùng thêm kem dưỡng phía sau không bị nặng mặt.'],
    ['Da ẩm hơn rõ rệt', 'Sau vài ngày dùng đều, bề mặt da mềm và đỡ khô căng hơn.'],
    ['Hợp routine phục hồi', 'Sản phẩm khá dịu, dùng khi da yếu vẫn tạo cảm giác dễ chịu.'],
    ['Dễ layer với sản phẩm khác', 'Không bị vón khi dùng cùng toner, kem dưỡng và chống nắng.'],
    ['Da trông mịn hơn', 'Độ ẩm được duy trì tốt nên lớp makeup sau đó cũng mượt hơn.'],
    ['Không gây châm chích mạnh', 'Da mình nhạy cảm nhẹ nhưng dùng đúng lượng vẫn ổn.'],
    ['Kết cấu đẹp, dùng tiết kiệm', 'Chỉ cần vài giọt là đủ cho toàn mặt và cổ.'],
    ['Phù hợp dùng mỗi ngày', 'Công thức dễ đưa vào routine sáng hoặc tối mà không quá phức tạp.'],
    ['Hiệu quả ổn định', 'Không phải kiểu thay đổi ngay lập tức nhưng da khỏe và đủ ẩm hơn theo thời gian.'],
    ['Đáng để mua lại', 'Trải nghiệm tốt từ kết cấu đến hiệu quả dưỡng, phù hợp nhu cầu hiện tại của mình.'],
  ],
  moisturizer: [
    ['Khóa ẩm tốt mà không nặng mặt', 'Kem tán dễ, giữ da mềm lâu nhưng không quá bí.'],
    ['Da mềm hơn vào sáng hôm sau', 'Dùng buổi tối giúp những vùng khô quanh mũi và má dễ chịu hơn.'],
    ['Kết cấu dễ dùng', 'Kem không quá đặc, thoa lên da nhanh tiệp và không bết lâu.'],
    ['Hợp với da thiếu ẩm', 'Sản phẩm giúp giảm cảm giác căng và làm bề mặt da mượt hơn.'],
    ['Dùng dưới makeup ổn', 'Lớp nền bám đều hơn và ít bị mốc ở vùng khô.'],
    ['Không gây bí da', 'Mình dùng lượng vừa phải và chưa thấy tình trạng nặng mặt hay nổi mụn bất thường.'],
    ['Phù hợp routine phục hồi', 'Khi da nhạy cảm nhẹ, kem tạo cảm giác êm và đủ ẩm.'],
    ['Giữ ẩm khá lâu', 'Sau nhiều giờ da vẫn mềm, đặc biệt khi ngồi phòng máy lạnh.'],
    ['Mùi nhẹ, dễ chịu', 'Không có mùi quá nồng nên dùng buổi tối rất thoải mái.'],
    ['Sẽ tiếp tục dùng', 'Hiệu quả dưỡng ẩm tốt và dễ kết hợp với các treatment khác.'],
  ],
  toner: [
    ['Cấp ẩm nhẹ và dễ chịu', 'Sau bước làm sạch, toner giúp da mềm hơn và bớt căng.'],
    ['Thấm nhanh, không dính', 'Kết cấu lỏng nhẹ, vỗ vài lần là ráo và tiếp tục routine được ngay.'],
    ['Dễ layer nhiều lớp', 'Dùng một đến hai lớp vẫn nhẹ mặt và không bị bết.'],
    ['Hợp với routine tối giản', 'Chỉ cần toner và kem dưỡng là da đã đủ ẩm trong những ngày bình thường.'],
    ['Da dịu hơn sau khi dùng', 'Cảm giác nóng rát nhẹ sau rửa mặt được giảm khá nhanh.'],
    ['Không có mùi nồng', 'Trải nghiệm dễ chịu, phù hợp với người không thích hương liệu mạnh.'],
    ['Dùng hằng ngày rất ổn', 'Sản phẩm nhẹ, ít gây xung đột với những bước dưỡng khác.'],
    ['Da mịn hơn trước makeup', 'Bề mặt da đủ ẩm nên lớp nền sau đó tán đều hơn.'],
    ['Chai dùng khá tiết kiệm', 'Mỗi lần chỉ cần lượng nhỏ và có thể dùng bằng tay.'],
    ['Mình sẽ mua lại', 'Khả năng cấp ẩm và làm dịu ổn định, phù hợp nhu cầu cơ bản.'],
  ],
  lip: [
    ['Màu lên đẹp và dễ dùng', 'Màu son tôn da, có thể đánh lòng môi hoặc full môi đều đẹp.'],
    ['Chất son mượt', 'Son lướt êm, không kéo môi và không làm lộ vân quá nhiều.'],
    ['Màu đúng như mong đợi', 'Tông màu thực tế khá gần hình, phù hợp makeup hằng ngày.'],
    ['Độ bám màu tốt', 'Sau ăn nhẹ màu vẫn còn tương đối đều, chỉ cần dặm lại một chút.'],
    ['Không làm môi quá khô', 'Môi mình dễ khô nhưng dùng son vẫn khá thoải mái nếu dưỡng trước.'],
    ['Dễ phối nhiều kiểu makeup', 'Màu son hợp cả phong cách tự nhiên lẫn trang điểm đậm hơn.'],
    ['Bao bì đẹp, cầm chắc tay', 'Thiết kế gọn và tiện mang theo trong túi.'],
    ['Hiệu ứng môi đẹp', 'Finish làm môi trông đầy đặn và màu lên đều.'],
    ['Rất hợp dùng đi làm', 'Màu vừa đủ nổi bật nhưng vẫn thanh lịch và dễ dùng.'],
    ['Sẽ mua thêm màu khác', 'Chất lượng tốt, màu đẹp và trải nghiệm sử dụng rất ổn.'],
  ],
  base: [
    ['Lớp nền mịn và tự nhiên', 'Sản phẩm tán dễ, che phủ vừa phải và không làm mặt bị dày.'],
    ['Tiệp da khá tốt', 'Màu nền hợp với tone da và sau khi tán nhìn khá tự nhiên.'],
    ['Độ che phủ ổn', 'Các vùng đỏ nhẹ và thâm nhỏ được làm đều màu tốt.'],
    ['Không bị cakey nhiều', 'Khi dưỡng ẩm kỹ, nền giữ được độ mượt trong nhiều giờ.'],
    ['Dễ dặm lại', 'Sản phẩm không bị mốc quá nhiều khi cần bổ sung giữa ngày.'],
    ['Finish đẹp', 'Da trông sáng và đều màu nhưng vẫn giữ được độ tự nhiên.'],
    ['Hợp makeup hằng ngày', 'Không quá nặng mặt, dùng đi làm hoặc đi học rất tiện.'],
    ['Bám khá tốt', 'Trong thời tiết nóng, lớp nền vẫn giữ ổn nếu phủ phấn nhẹ.'],
    ['Không làm lộ lỗ chân lông nhiều', 'Bề mặt da trông mịn hơn khi dùng lượng vừa phải.'],
    ['Đáng mua lại', 'Tổng thể từ màu, độ che phủ đến cảm giác trên da đều tốt.'],
  ],
  mascara: [
    ['Giữ cong mi tốt', 'Mi giữ độ cong khá lâu và không bị nặng dù chuốt hai lớp.'],
    ['Không lem nhiều', 'Trong ngày sản phẩm bám tốt, vùng dưới mắt vẫn khá sạch.'],
    ['Làm mi dài tự nhiên', 'Hiệu ứng tơi mi đẹp, không bị vón cục nếu chuốt từng lớp mỏng.'],
    ['Đầu cọ dễ dùng', 'Cọ ôm mi tốt và thao tác được cả những sợi mi ngắn.'],
    ['Hợp makeup hằng ngày', 'Mi rõ hơn nhưng vẫn tự nhiên, không quá dày.'],
    ['Khô nhanh vừa phải', 'Có đủ thời gian chỉnh mi nhưng không phải chờ quá lâu.'],
    ['Bám tốt trong thời tiết nóng', 'Mascara không trôi nhiều khi hoạt động ngoài trời.'],
    ['Tẩy trang không quá khó', 'Dùng sản phẩm tẩy trang mắt môi là làm sạch được khá nhanh.'],
    ['Mi trông dày hơn', 'Hiệu ứng làm dày ổn nhưng vẫn giữ được độ tơi.'],
    ['Sẽ mua lại', 'Khả năng giữ cong và chống lem đáp ứng tốt nhu cầu của mình.'],
  ],
  colorMakeup: [
    ['Màu lên chuẩn và dễ tán', 'Sắc độ đẹp, có thể tăng dần độ đậm mà không bị loang.'],
    ['Hợp makeup hằng ngày', 'Màu tự nhiên, dễ phối với nhiều tông son và kiểu trang điểm.'],
    ['Bột mịn, ít rơi', 'Kết cấu dễ lấy và tán khá đều trên da.'],
    ['Độ bám màu tốt', 'Sau vài giờ màu vẫn còn rõ và không xuống tông quá nhanh.'],
    ['Tông màu tôn da', 'Màu giúp gương mặt tươi hơn mà không bị quá đậm.'],
    ['Dễ kiểm soát lượng sản phẩm', 'Lấy ít một vẫn lên màu đẹp, phù hợp cả người mới trang điểm.'],
    ['Không làm nền bị mốc', 'Sản phẩm nằm trên lớp nền khá mượt và không tạo mảng.'],
    ['Bao bì gọn, tiện mang theo', 'Thiết kế nhỏ gọn nhưng vẫn chắc chắn.'],
    ['Phối màu rất dễ', 'Dùng riêng hoặc kết hợp các màu khác đều hài hòa.'],
    ['Đáng thử', 'Chất lượng màu và độ bám tốt trong tầm giá.'],
  ],
  generic: [
    ['Chất lượng tốt hơn mong đợi', 'Sản phẩm dễ dùng, cảm giác trên da thoải mái và hiệu quả đúng nhu cầu.'],
    ['Đúng mô tả và đóng gói kỹ', 'Nhận hàng nguyên vẹn, sản phẩm có trải nghiệm sử dụng tốt.'],
    ['Dùng hằng ngày rất ổn', 'Kết cấu dễ thao tác và không gây cảm giác nặng hoặc khó chịu.'],
    ['Phù hợp với mình', 'Sau một thời gian sử dụng, mình thấy sản phẩm đáp ứng tốt nhu cầu hiện tại.'],
    ['Trải nghiệm tổng thể tốt', 'Từ thiết kế, kết cấu đến hiệu quả đều khá chỉn chu.'],
    ['Dễ kết hợp trong routine', 'Sản phẩm không gây xung đột với các bước mình đang dùng.'],
    ['Hiệu quả ổn định', 'Không quá phô trương nhưng dùng đều cho kết quả khá tốt.'],
    ['Giá hợp lý so với chất lượng', 'Chất lượng sản phẩm tương xứng và có thể dùng lâu dài.'],
    ['Sẽ giới thiệu cho bạn bè', 'Sản phẩm dễ dùng và phù hợp với nhiều nhu cầu cơ bản.'],
    ['Có khả năng mua lại', 'Mình hài lòng với trải nghiệm và sẽ cân nhắc mua lại khi dùng hết.'],
  ],
};

function deterministicObjectId(...parts) {
  const source = [SEED_NAMESPACE, ...parts.map(String)].join(':');
  const hex = crypto.createHash('md5').update(source).digest('hex').slice(0, 24);
  return new ObjectId(hex);
}

function normalizeObjectId(value) {
  if (!value) return null;
  if (value instanceof ObjectId) return value;
  return new ObjectId(String(value));
}

function pad(value, width = 2) {
  return String(value).padStart(width, '0');
}

function daysAgo(days) {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() - days);
  date.setUTCHours(3 + (days % 11), (days * 7) % 60, (days * 13) % 60, 0);
  return date;
}

function pick(array, index) {
  return array[index % array.length];
}

function cleanText(value) {
  return String(value || '').trim();
}

function productName(product) {
  return cleanText(product.productName || product.product_name || product.name) || `Sản phẩm ${String(product._id).slice(-6)}`;
}

function productPrice(product) {
  const candidates = [
    product.price,
    product.salePriceAmount,
    product.sale_price_amount,
    product.finalPrice,
    product.final_price,
    product.compareAtPrice,
  ];
  for (const value of candidates) {
    const parsed = Number(value);
    if (Number.isFinite(parsed) && parsed >= 0) return Math.round(parsed);
  }
  return 199000;
}

function variantName(variant) {
  return cleanText(variant.variantName || variant.variant_name || variant.sku) || `Biến thể ${String(variant._id).slice(-6)}`;
}

function variantSku(variant, productIndex, reviewIndex) {
  return cleanText(variant.sku || variant.SKU) || `KNL-REVIEW-${pad(productIndex + 1, 4)}-${pad(reviewIndex + 1, 2)}`;
}

function variantProductId(variant) {
  return normalizeObjectId(variant.productId || variant.product_id || variant.product || null);
}

function detectProductType(product) {
  const haystack = [
    productName(product),
    product.shortDescription,
    product.longDescription,
    product.productCode,
    product.slug,
  ].map((value) => cleanText(value).toLowerCase()).join(' ');

  const hasAny = (...keywords) => keywords.some((keyword) => haystack.includes(keyword));

  if (hasAny('sữa rửa mặt', 'cleanser', 'cleansing foam', 'face wash', 'perfect whip')) return 'cleanser';
  if (hasAny('tẩy trang', 'micellar', 'cleansing water', 'cleansing oil', 'makeup remover')) return 'micellar';
  if (hasAny('chống nắng', 'sunscreen', 'sun cream', 'uv ', 'spf')) return 'sunscreen';
  if (hasAny('serum', 'essence', 'ampoule', 'tinh chất')) return 'serum';
  if (hasAny('kem dưỡng', 'moisturizer', 'cream', 'gel cream', 'sleeping mask')) return 'moisturizer';
  if (hasAny('toner', 'lotion', 'nước cân bằng')) return 'toner';
  if (hasAny('son', 'lip tint', 'lipstick', 'lip glow', 'lip balm', 'tint')) return 'lip';
  if (hasAny('kem nền', 'foundation', 'cushion', 'concealer', 'che khuyết điểm', 'primer')) return 'base';
  if (hasAny('mascara', 'eyeliner', 'kẻ mắt')) return 'mascara';
  if (hasAny('má hồng', 'blush', 'phấn mắt', 'eyeshadow', 'highlighter', 'bronzer', 'phấn phủ', 'powder')) return 'colorMakeup';
  return 'generic';
}

function buildPositiveReview(product, reviewIndex, globalIndex) {
  const type = detectProductType(product);
  const library = REVIEW_LIBRARY[type] || REVIEW_LIBRARY.generic;
  const [title, coreContent] = pick(library, reviewIndex);
  const context = pick(USAGE_CONTEXTS, globalIndex);
  const skin = pick(SKIN_CONTEXTS, globalIndex + reviewIndex);
  const name = productName(product);

  return {
    title: title || pick(GENERIC_TITLES, globalIndex),
    content: `${coreContent} Mình có ${skin}, ${context} và thấy ${name} khá dễ dùng. Hàng nhận đúng mô tả, bao bì nguyên vẹn.`,
  };
}

function buildOrderNumber(productIndex, reviewIndex) {
  return `KRV${new Date().getUTCFullYear()}${pad(productIndex + 1, 4)}${pad(reviewIndex + 1, 2)}`;
}

function customerDisplayName(customer, fallbackIndex) {
  return cleanText(customer.full_name || customer.fullName || customer.name) || `Khách hàng Kanila ${pad(fallbackIndex + 1, 3)}`;
}

function customerPhone(customer, fallbackIndex) {
  const existing = cleanText(customer.phone || customer.phone_number);
  if (existing) return existing;
  return `09${String(10000000 + ((fallbackIndex + 1) * 7919)).slice(-8)}`;
}

async function connectMongo() {
  const uri = process.env.MONGODB_URI
    || process.env.MONGO_URI
    || process.env.MONGODB_URL
    || process.env.DATABASE_URL;

  if (!uri) {
    throw new Error('Missing MongoDB connection string. Set MONGODB_URI or MONGO_URI in .env');
  }

  const options = process.env.MONGODB_DB_NAME
    ? { dbName: process.env.MONGODB_DB_NAME }
    : undefined;

  await mongoose.connect(uri, options);
  console.log(`Connected to MongoDB database: ${mongoose.connection.name}`);
}

async function getCollectionNames(db) {
  const rows = await db.listCollections({}, { nameOnly: true }).toArray();
  return new Set(rows.map((row) => row.name));
}

async function loadContext(db) {
  const products = await db.collection(COLLECTION.products)
    .find({})
    .sort({ _id: 1 })
    .toArray();

  if (!products.length) {
    throw new Error('No products found. Run dataproduct_copy.js before datareview.js.');
  }

  const variants = await db.collection(COLLECTION.variants)
    .find({})
    .sort({ _id: 1 })
    .toArray();

  if (!variants.length) {
    throw new Error('No product_variants found. Run dataproduct_copy.js before datareview.js.');
  }

  const customers = await db.collection(COLLECTION.customers)
    .find({})
    .sort({ _id: 1 })
    .toArray();

  if (customers.length < REVIEWS_PER_PRODUCT) {
    throw new Error(
      `Only ${customers.length} customer_profiles found. `
      + `At least ${REVIEWS_PER_PRODUCT} customers are required so each product can receive distinct reviews. `
      + 'Run dataremaining.js first.',
    );
  }

  const customerAddresses = await db.collection(COLLECTION.customerAddresses)
    .find({})
    .sort({ _id: 1 })
    .toArray();

  const variantsByProduct = new Map();
  for (const variant of variants) {
    const productId = variantProductId(variant);
    if (!productId) continue;
    const key = String(productId);
    if (!variantsByProduct.has(key)) variantsByProduct.set(key, []);
    variantsByProduct.get(key).push(variant);
  }

  const addressByCustomer = new Map();
  for (const address of customerAddresses) {
    if (!address.customer_id) continue;
    const key = String(address.customer_id);
    if (!addressByCustomer.has(key) || address.is_default_shipping) {
      addressByCustomer.set(key, address);
    }
  }

  const productsWithoutVariants = products.filter((product) => !variantsByProduct.has(String(product._id)));
  if (productsWithoutVariants.length) {
    const names = productsWithoutVariants.slice(0, 5).map(productName).join(', ');
    throw new Error(
      `${productsWithoutVariants.length} products do not have mapped variants. `
      + `Examples: ${names}. Check product_variants.productId/product_id before seeding reviews.`,
    );
  }

  return {
    products,
    customers,
    variantsByProduct,
    addressByCustomer,
  };
}

function buildSeedDocuments(ctx) {
  const orders = [];
  const orderItems = [];
  const orderTotals = [];
  const orderAddresses = [];
  const orderStatusHistory = [];
  const reviews = [];

  ctx.products.forEach((product, productIndex) => {
    const productVariants = ctx.variantsByProduct.get(String(product._id));

    for (let reviewIndex = 0; reviewIndex < REVIEWS_PER_PRODUCT; reviewIndex += 1) {
      const globalIndex = productIndex * REVIEWS_PER_PRODUCT + reviewIndex;
      const customer = ctx.customers[(globalIndex + productIndex) % ctx.customers.length];
      const variant = productVariants[reviewIndex % productVariants.length];

      const orderId = deterministicObjectId('order', product._id, reviewIndex);
      const orderItemId = deterministicObjectId('order-item', product._id, reviewIndex);
      const orderTotalId = deterministicObjectId('order-total', product._id, reviewIndex);
      const orderAddressId = deterministicObjectId('order-address', product._id, reviewIndex);
      const orderStatusHistoryId = deterministicObjectId('order-status-history', product._id, reviewIndex);
      const reviewId = deterministicObjectId('review', product._id, reviewIndex);

      const placedAt = daysAgo(150 - ((globalIndex * 3) % 120));
      const confirmedAt = new Date(placedAt.getTime() + 4 * 60 * 60 * 1000);
      const completedAt = new Date(placedAt.getTime() + (3 + (reviewIndex % 4)) * 24 * 60 * 60 * 1000);
      const reviewedAt = new Date(completedAt.getTime() + (2 + (reviewIndex % 12)) * 24 * 60 * 60 * 1000);

      const listPrice = productPrice(product);
      const discountRate = reviewIndex % 4 === 0 ? 0.1 : reviewIndex % 5 === 0 ? 0.05 : 0;
      const finalPrice = Math.max(0, Math.round((listPrice * (1 - discountRate)) / 1000) * 1000);
      const discountAmount = listPrice - finalPrice;
      const shippingFee = reviewIndex % 3 === 0 ? 0 : 25000;
      const grandTotal = finalPrice + shippingFee;
      const orderNumber = buildOrderNumber(productIndex, reviewIndex);
      const rating = RATING_PATTERN[reviewIndex % RATING_PATTERN.length];
      const reviewText = buildPositiveReview(product, reviewIndex, globalIndex);
      const address = ctx.addressByCustomer.get(String(customer._id));

      orders.push({
        _id: orderId,
        owner_type: 'customer',
        guest_session_id: null,
        guest_email: '',
        guest_phone: '',
        guest_full_name: '',
        order_number: orderNumber,
        customer_id: customer._id,
        checkout_session_id: null,
        currency_code: 'VND',
        order_status: 'completed',
        payment_status: 'paid',
        fulfillment_status: 'delivered',
        customer_note: 'Đơn hàng mock phục vụ dữ liệu đánh giá sản phẩm Kanila.',
        placed_at: placedAt,
        confirmed_at: confirmedAt,
        cancelled_at: null,
        completed_at: completedAt,
        cancellation_reason: '',
        created_at: placedAt,
        updated_at: completedAt,
        __v: 0,
      });

      orderItems.push({
        _id: orderItemId,
        order_id: orderId,
        product_id: product._id,
        variant_id: variant._id,
        sku_snapshot: variantSku(variant, productIndex, reviewIndex),
        product_name_snapshot: productName(product),
        variant_name_snapshot: variantName(variant),
        quantity: 1,
        unit_list_price_amount: listPrice,
        unit_sale_price_amount: finalPrice,
        unit_final_price_amount: finalPrice,
        line_subtotal_amount: listPrice,
        line_discount_amount: discountAmount,
        line_total_amount: finalPrice,
        currency_code: 'VND',
        created_at: placedAt,
        updated_at: completedAt,
        __v: 0,
      });

      orderTotals.push({
        _id: orderTotalId,
        order_id: orderId,
        subtotal_amount: listPrice,
        item_discount_amount: discountAmount,
        order_discount_amount: 0,
        shipping_fee_amount: shippingFee,
        tax_amount: 0,
        grand_total_amount: grandTotal,
        refunded_amount: 0,
        currency_code: 'VND',
        created_at: placedAt,
        updated_at: completedAt,
        __v: 0,
      });

      orderAddresses.push({
        _id: orderAddressId,
        order_id: orderId,
        address_type: 'shipping',
        recipient_name: address?.recipient_name || customerDisplayName(customer, globalIndex),
        phone: address?.phone || customerPhone(customer, globalIndex),
        address_line_1: address?.address_line_1 || `${20 + (globalIndex % 180)} đường Kanila Beauty`,
        address_line_2: address?.address_line_2 || '',
        ward: address?.ward || 'Phường Bến Nghé',
        district: address?.district || 'Quận 1',
        city: address?.city || 'TP. Hồ Chí Minh',
        country_code: address?.country_code || 'VN',
        postal_code: address?.postal_code || '700000',
        created_at: placedAt,
        __v: 0,
      });

      orderStatusHistory.push({
        _id: orderStatusHistoryId,
        order_id: orderId,
        old_order_status: 'processing',
        new_order_status: 'completed',
        old_payment_status: 'authorized',
        new_payment_status: 'paid',
        old_fulfillment_status: 'shipped',
        new_fulfillment_status: 'delivered',
        changed_by_account_id: null,
        change_reason: 'Đơn hàng đã giao thành công và đủ điều kiện đánh giá.',
        changed_at: completedAt,
        __v: 0,
      });

      reviews.push({
        _id: reviewId,
        customer_id: customer._id,
        orderItemId,
        productId: product._id,
        variantId: variant._id,
        rating,
        reviewTitle: reviewText.title,
        reviewContent: reviewText.content,
        reviewStatus: 'visible',
        helpfulCount: (productIndex * 7 + reviewIndex * 3) % 36,
        verifiedPurchaseFlag: true,
        createdAt: reviewedAt,
        updatedAt: reviewedAt,
        __v: 0,
      });
    }
  });

  return {
    orders,
    orderItems,
    orderTotals,
    orderAddresses,
    orderStatusHistory,
    reviews,
  };
}

async function resetGeneratedRows(db, docs) {
  if (!SHOULD_RESET) return;

  console.log('Reset mode: deleting rows generated by datareview.js...');
  const resetPlan = [
    [COLLECTION.reviews, docs.reviews],
    [COLLECTION.orderStatusHistory, docs.orderStatusHistory],
    [COLLECTION.orderAddresses, docs.orderAddresses],
    [COLLECTION.orderTotals, docs.orderTotals],
    [COLLECTION.orderItems, docs.orderItems],
    [COLLECTION.orders, docs.orders],
  ];

  for (const [collectionName, rows] of resetPlan) {
    const ids = rows.map((row) => row._id);
    const result = await db.collection(collectionName).deleteMany({ _id: { $in: ids } });
    console.log(`  ${collectionName.padEnd(28)} deleted ${String(result.deletedCount).padStart(5)}`);
  }
}

async function replaceManyById(db, collectionName, docs) {
  if (!docs.length) return;

  const operations = docs.map((doc) => ({
    replaceOne: {
      filter: { _id: doc._id },
      replacement: doc,
      upsert: true,
    },
  }));

  const result = await db.collection(collectionName).bulkWrite(operations, { ordered: false });
  console.log(
    `${collectionName.padEnd(28)} prepared ${String(docs.length).padStart(5)}`
    + ` | upserted ${String(result.upsertedCount || 0).padStart(5)}`
    + ` | modified ${String(result.modifiedCount || 0).padStart(5)}`,
  );
}

async function synchronizeReviewSummaries(db, products, collectionNames) {
  let summaryCollection = 'review_summary';
  if (collectionNames.has('review_summary')) summaryCollection = 'review_summary';
  else if (collectionNames.has('review_summaries')) summaryCollection = 'review_summaries';

  const productIds = products.map((product) => product._id);
  const aggregateRows = await db.collection(COLLECTION.reviews).aggregate([
    {
      $match: {
        productId: { $in: productIds },
        reviewStatus: 'visible',
      },
    },
    {
      $group: {
        _id: '$productId',
        reviewCount: { $sum: 1 },
        averageRating: { $avg: '$rating' },
        rating1Count: { $sum: { $cond: [{ $eq: ['$rating', 1] }, 1, 0] } },
        rating2Count: { $sum: { $cond: [{ $eq: ['$rating', 2] }, 1, 0] } },
        rating3Count: { $sum: { $cond: [{ $eq: ['$rating', 3] }, 1, 0] } },
        rating4Count: { $sum: { $cond: [{ $eq: ['$rating', 4] }, 1, 0] } },
        rating5Count: { $sum: { $cond: [{ $eq: ['$rating', 5] }, 1, 0] } },
      },
    },
  ]).toArray();

  const byProduct = new Map(aggregateRows.map((row) => [String(row._id), row]));
  const now = new Date();
  const operations = products.map((product) => {
    const aggregate = byProduct.get(String(product._id)) || {
      reviewCount: 0,
      averageRating: 0,
      rating1Count: 0,
      rating2Count: 0,
      rating3Count: 0,
      rating4Count: 0,
      rating5Count: 0,
    };

    return {
      updateOne: {
        filter: { productId: product._id },
        update: {
          $set: {
            productId: product._id,
            reviewCount: aggregate.reviewCount,
            averageRating: Number((aggregate.averageRating || 0).toFixed(2)),
            rating1Count: aggregate.rating1Count,
            rating2Count: aggregate.rating2Count,
            rating3Count: aggregate.rating3Count,
            rating4Count: aggregate.rating4Count,
            rating5Count: aggregate.rating5Count,
            updatedAt: now,
            __v: 0,
          },
          $setOnInsert: {
            _id: deterministicObjectId('review-summary', product._id),
            createdAt: now,
          },
        },
        upsert: true,
      },
    };
  });

  const result = await db.collection(summaryCollection).bulkWrite(operations, { ordered: false });
  console.log(
    `${summaryCollection.padEnd(28)} synchronized ${String(products.length).padStart(5)}`
    + ` | upserted ${String(result.upsertedCount || 0).padStart(5)}`
    + ` | modified ${String(result.modifiedCount || 0).padStart(5)}`,
  );
}

async function verify(db, products) {
  const generatedReviewIds = [];
  for (const product of products) {
    for (let reviewIndex = 0; reviewIndex < REVIEWS_PER_PRODUCT; reviewIndex += 1) {
      generatedReviewIds.push(deterministicObjectId('review', product._id, reviewIndex));
    }
  }

  const generatedReviewCount = await db.collection(COLLECTION.reviews).countDocuments({
    _id: { $in: generatedReviewIds },
  });

  const perProduct = await db.collection(COLLECTION.reviews).aggregate([
    {
      $match: {
        _id: { $in: generatedReviewIds },
        reviewStatus: 'visible',
        rating: { $in: [4, 5] },
        verifiedPurchaseFlag: true,
      },
    },
    { $group: { _id: '$productId', count: { $sum: 1 }, averageRating: { $avg: '$rating' } } },
    { $sort: { count: 1 } },
  ]).toArray();

  const invalidProducts = perProduct.filter((row) => row.count !== REVIEWS_PER_PRODUCT);
  if (generatedReviewCount !== products.length * REVIEWS_PER_PRODUCT || invalidProducts.length) {
    throw new Error(
      `Verification failed. Expected ${products.length * REVIEWS_PER_PRODUCT} generated reviews, `
      + `found ${generatedReviewCount}; products with invalid review counts: ${invalidProducts.length}.`,
    );
  }

  const minAverage = Math.min(...perProduct.map((row) => row.averageRating));
  const maxAverage = Math.max(...perProduct.map((row) => row.averageRating));

  console.log('\nVerification passed:');
  console.log(`  Products covered       : ${products.length}`);
  console.log(`  Reviews per product    : ${REVIEWS_PER_PRODUCT}`);
  console.log(`  Generated reviews      : ${generatedReviewCount}`);
  console.log(`  Ratings                : only 4-5 stars`);
  console.log(`  Verified purchases     : 100%`);
  console.log(`  Average rating range   : ${minAverage.toFixed(2)} - ${maxAverage.toFixed(2)}`);
}

async function run() {
  await connectMongo();
  const db = mongoose.connection.db;
  const collectionNames = await getCollectionNames(db);
  const context = await loadContext(db);
  const docs = buildSeedDocuments(context);

  console.log(`Products found: ${context.products.length}`);
  console.log(`Customers found: ${context.customers.length}`);
  console.log(`Reviews per product: ${REVIEWS_PER_PRODUCT}`);
  console.log(`Total review-linked orders to prepare: ${docs.orders.length}\n`);

  await resetGeneratedRows(db, docs);

  const seedPlan = [
    [COLLECTION.orders, docs.orders],
    [COLLECTION.orderItems, docs.orderItems],
    [COLLECTION.orderTotals, docs.orderTotals],
    [COLLECTION.orderAddresses, docs.orderAddresses],
    [COLLECTION.orderStatusHistory, docs.orderStatusHistory],
    [COLLECTION.reviews, docs.reviews],
  ];

  for (const [collectionName, rows] of seedPlan) {
    await replaceManyById(db, collectionName, rows);
  }

  await synchronizeReviewSummaries(db, context.products, collectionNames);
  await verify(db, context.products);

  console.log('\nKanila review seed completed successfully.');
}

run()
  .then(async () => {
    await mongoose.disconnect();
    process.exit(0);
  })
  .catch(async (error) => {
    console.error('\nKanila review seed failed:', error);
    try {
      await mongoose.disconnect();
    } catch (_) {
      // Ignore disconnect errors while handling the original failure.
    }
    process.exit(1);
  });
