/**
 * dataAR.js
 * Kanila Beauty Commerce - AR Try-On data synchronizer/seed.
 *
 * Purpose
 * -------
 * Reads the existing normalized catalog generated by dataproduct*.js and the
 * pricing/inventory/media data generated by dataremaining.js, then:
 *
 * 1. Enables AR only for products supported by the current Android renderer:
 *      LIPS   -> lipstick, lip tint, coloured lip balm/lip gloss
 *      CHEEKS -> blush
 *      EYES   -> eyeshadow
 * 2. Sets products.hasAr = true and compatible AR metadata.
 * 3. Creates/updates one document per product in product_ar_configs.
 * 4. Adds AR-related product_attributes for eligible products.
 * 5. Resolves variant price, inventory and thumbnail from canonical collections,
 *    with safe catalog fallbacks when dataremaining.js has no row for a variant.
 *
 * Important classification rule
 * -----------------------------
 * Do NOT map foundation, cushion, concealer, powder, primer, mascara, eyebrow,
 * eyeliner or skincare products to LIPS/CHEEKS/EYES. The current renderer only
 * supports the three regions above. Unsupported categories remain unchanged,
 * unless --sync-all is explicitly passed.
 *
 * Run from backend root
 * ---------------------
 *   npm install dotenv mongoose
 *   node dataAR.js --dry-run
 *   node dataAR.js
 *
 * Optional flags
 * --------------
 *   --dry-run       Preview all actions without writing to MongoDB.
 *   --sync-all      Also set hasAr=false for unsupported products and disable
 *                   stale configs previously managed by this script.
 *   --reset         Remove only data managed by this seed batch before syncing.
 *   --self-test     Run pure classification/profile tests without MongoDB deps.
 *   --product-id=X  Sync only one product ObjectId.
 *
 * Environment
 * -----------
 *   MONGODB_URI | MONGO_URI | MONGODB_URL | DATABASE_URL
 *   MONGODB_DB_NAME (optional)
 *   AR_CONFIG_COLLECTION (default: product_ar_configs)
 *   AR_RENDERER_VERSION (default: v2)
 */

'use strict';

const crypto = require('crypto');

// Load .env when dotenv is available. Self-test remains dependency-free.
try {
  require('dotenv').config();
} catch (_) {
  // Database mode will emit a clear dependency error from connectMongo().
}

const SEED_BATCH = 'kanila_ar_v1';
const DEFAULT_RENDERER_VERSION = process.env.AR_RENDERER_VERSION || 'v2';
const DRY_RUN = process.argv.includes('--dry-run');
const RESET = process.argv.includes('--reset');
const SYNC_ALL = process.argv.includes('--sync-all');
const SELF_TEST = process.argv.includes('--self-test');
const PRODUCT_ID_ARG = process.argv.find((arg) => arg.startsWith('--product-id='));
const ONLY_PRODUCT_ID = PRODUCT_ID_ARG ? PRODUCT_ID_ARG.split('=').slice(1).join('=').trim() : null;

const COLLECTION = Object.freeze({
  products: 'products',
  categories: 'categories',
  variants: 'product_variants',
  variantMedia: 'variant_medias',
  productMedia: 'product_media',
  inventoryBalances: 'inventory_balances',
  priceBookEntries: 'price_book_entries',
  productAttributes: 'product_attributes',
  arConfigs: process.env.AR_CONFIG_COLLECTION || 'product_ar_configs',
});

const SUPPORTED_CATEGORY_RULES = Object.freeze({
  LIPS: new Set([
    'CAT_LIPSTICK',
    'CAT_LIP_TINT',
    'CAT_LIP_BALM',
    'CAT_LIP_GLOSS',
    'CAT_LIP_STAIN',
  ]),
  CHEEKS: new Set([
    'CAT_BLUSH',
    'CAT_CHEEK_TINT',
  ]),
  EYES: new Set([
    'CAT_EYESHADOW',
  ]),
});

const CATEGORY_NAME_ALIASES = Object.freeze({
  LIPS: [
    'son moi', 'son thoi', 'son tint', 'son duong co mau', 'son bong', 'lipstick', 'lip tint', 'lip balm', 'lip gloss',
  ],
  CHEEKS: [
    'ma hong', 'phan ma', 'blush', 'cheek tint',
  ],
  EYES: [
    'phan mat', 'mau mat', 'eyeshadow', 'eye shadow',
  ],
});

const AR_REGION_LABELS = Object.freeze({
  LIPS: 'Môi',
  CHEEKS: 'Gò má',
  EYES: 'Mí mắt và hốc mắt',
});

const AR_ATTRIBUTE_NAMES = Object.freeze([
  'AR Try-On',
  'AR Type',
  'Vùng mô phỏng AR',
  'Phiên bản AR Renderer',
  'Số biến thể AR',
]);

const DISCLAIMER = 'Màu thực tế có thể thay đổi tùy ánh sáng, camera, màu da/môi tự nhiên và màn hình.';

function clamp(value, min, max) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return min;
  return Math.min(max, Math.max(min, numeric));
}

function normalizeText(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function normalizeHex(value) {
  const raw = String(value || '').trim();
  const withHash = raw.startsWith('#') ? raw : `#${raw}`;
  if (!/^#[0-9a-fA-F]{6}$/.test(withHash)) return null;
  return withHash.toUpperCase();
}

function normalizeId(value) {
  if (!value) return null;
  if (typeof value === 'object' && value._id) return value._id;
  return value;
}

function productName(product) {
  return product.productName || product.product_name || product.name || `Product ${String(product._id || '')}`;
}

function productPrice(product) {
  return Number(product.price || product.salePriceAmount || product.sale_price_amount || product.final_price || 0);
}

function productStock(product) {
  return Math.max(0, Number(product.stock || product.availableQty || product.available_qty || 0));
}

function variantProductId(variant) {
  return normalizeId(variant.productId || variant.product_id || variant.product || null);
}

function variantName(variant) {
  return variant.variantName || variant.variant_name || variant.name || variant.sku || `Variant ${String(variant._id || '')}`;
}

function variantSku(variant) {
  return variant.sku || variant.SKU || '';
}

function deterministicObjectIdHex(key) {
  return crypto.createHash('md5').update(`${SEED_BATCH}:${key}`).digest('hex').slice(0, 24);
}

function inferArType(category) {
  const code = String(category?.categoryCode || category?.category_code || category?.code || '').trim().toUpperCase();

  for (const [arType, codes] of Object.entries(SUPPORTED_CATEGORY_RULES)) {
    if (codes.has(code)) return arType;
  }

  const normalizedName = normalizeText(category?.categoryName || category?.category_name || category?.name || '');
  for (const [arType, aliases] of Object.entries(CATEGORY_NAME_ALIASES)) {
    if (aliases.some((alias) => normalizedName === normalizeText(alias) || normalizedName.includes(normalizeText(alias)))) {
      return arType;
    }
  }

  return null;
}

function normalizeShadeEntry(entry, index) {
  if (!entry) return null;

  if (Array.isArray(entry)) {
    const [name, hex, undertone] = entry;
    const normalizedHex = normalizeHex(hex);
    if (!normalizedHex) return null;
    return {
      name: String(name || `Shade ${index + 1}`).trim(),
      hex: normalizedHex,
      undertone: String(undertone || '').trim().toLowerCase() || null,
    };
  }

  const name = entry.name || entry.shadeName || entry.shade_name || entry.variantName || entry.variant_name;
  const hex = entry.hex || entry.colorCode || entry.color_code || entry.shadeHex || entry.shade_hex;
  const normalizedHex = normalizeHex(hex);
  if (!normalizedHex) return null;

  return {
    name: String(name || `Shade ${index + 1}`).trim(),
    hex: normalizedHex,
    undertone: String(entry.undertone || '').trim().toLowerCase() || null,
  };
}

function productShades(product) {
  const raw = Array.isArray(product.shades) ? product.shades : [];
  return raw.map(normalizeShadeEntry).filter(Boolean);
}

function mapFinishType(product, arType) {
  const finish = normalizeText(product.finish_type || product.finish || product.texture || '');
  const category = normalizeText(product.categoryCode || product.category_code || '');

  if (/matte|velvet|semi matte/.test(finish)) return 'MATTE';
  if (/gloss|glossy|shine|glow|shimmer|metallic|pearl/.test(finish)) return 'GLOSSY';
  if (/tint|stain|water gel|sheer/.test(finish) || /lip tint|lip stain/.test(category)) return 'TINT';
  if (/satin|natural|cream|creamy/.test(finish)) return 'SATIN';

  if (arType === 'CHEEKS') return 'SATIN';
  if (arType === 'EYES') return 'SATIN';
  return 'TINT';
}

const BASE_RENDER_PROFILES = Object.freeze({
  LIPS: Object.freeze({
    MATTE: Object.freeze({ opacity: 0.68, coverage: 0.82, edge_feather: 0.10, texture_retention: 0.62, saturation: 0.96, brightness_bias: -0.01, roughness: 0.85, specular_strength: 0.06 }),
    GLOSSY: Object.freeze({ opacity: 0.52, coverage: 0.66, edge_feather: 0.14, texture_retention: 0.80, saturation: 0.92, brightness_bias: 0.02, roughness: 0.30, specular_strength: 0.32 }),
    SATIN: Object.freeze({ opacity: 0.58, coverage: 0.72, edge_feather: 0.12, texture_retention: 0.74, saturation: 0.94, brightness_bias: 0.01, roughness: 0.55, specular_strength: 0.16 }),
    TINT: Object.freeze({ opacity: 0.44, coverage: 0.58, edge_feather: 0.16, texture_retention: 0.86, saturation: 0.90, brightness_bias: 0.00, roughness: 0.48, specular_strength: 0.12 }),
  }),
  CHEEKS: Object.freeze({
    MATTE: Object.freeze({ opacity: 0.34, coverage: 0.52, edge_feather: 0.28, texture_retention: 0.90, saturation: 0.86, brightness_bias: 0.00, roughness: 0.80, specular_strength: 0.03 }),
    GLOSSY: Object.freeze({ opacity: 0.27, coverage: 0.42, edge_feather: 0.32, texture_retention: 0.93, saturation: 0.84, brightness_bias: 0.02, roughness: 0.35, specular_strength: 0.20 }),
    SATIN: Object.freeze({ opacity: 0.31, coverage: 0.48, edge_feather: 0.30, texture_retention: 0.92, saturation: 0.85, brightness_bias: 0.01, roughness: 0.58, specular_strength: 0.10 }),
    TINT: Object.freeze({ opacity: 0.25, coverage: 0.40, edge_feather: 0.34, texture_retention: 0.95, saturation: 0.82, brightness_bias: 0.00, roughness: 0.50, specular_strength: 0.07 }),
  }),
  EYES: Object.freeze({
    MATTE: Object.freeze({ opacity: 0.48, coverage: 0.66, edge_feather: 0.18, texture_retention: 0.76, saturation: 0.94, brightness_bias: -0.01, roughness: 0.82, specular_strength: 0.04 }),
    GLOSSY: Object.freeze({ opacity: 0.40, coverage: 0.56, edge_feather: 0.20, texture_retention: 0.82, saturation: 0.96, brightness_bias: 0.02, roughness: 0.28, specular_strength: 0.28 }),
    SATIN: Object.freeze({ opacity: 0.44, coverage: 0.60, edge_feather: 0.19, texture_retention: 0.80, saturation: 0.95, brightness_bias: 0.01, roughness: 0.52, specular_strength: 0.14 }),
    TINT: Object.freeze({ opacity: 0.34, coverage: 0.48, edge_feather: 0.22, texture_retention: 0.88, saturation: 0.90, brightness_bias: 0.00, roughness: 0.50, specular_strength: 0.10 }),
  }),
});

function renderProfile(product, arType, finishType) {
  const base = BASE_RENDER_PROFILES[arType]?.[finishType] || BASE_RENDER_PROFILES.LIPS.TINT;
  const coverageType = normalizeText(product.coverage_type || product.coverage || '');
  let opacityAdjustment = 0;

  if (/full|high/.test(coverageType)) opacityAdjustment += 0.06;
  else if (/sheer|light/.test(coverageType)) opacityAdjustment -= 0.07;
  else if (/buildable/.test(coverageType)) opacityAdjustment -= 0.02;

  return {
    opacity: Number(clamp(base.opacity + opacityAdjustment, 0.12, 0.86).toFixed(2)),
    coverage: Number(clamp(base.coverage, 0, 1).toFixed(2)),
    edge_feather: Number(clamp(base.edge_feather, 0, 1).toFixed(2)),
    texture_retention: Number(clamp(base.texture_retention, 0, 1).toFixed(2)),
    saturation: Number(clamp(base.saturation, 0, 1.25).toFixed(2)),
    brightness_bias: Number(clamp(base.brightness_bias, -0.20, 0.20).toFixed(2)),
    roughness: Number(clamp(base.roughness, 0, 1).toFixed(2)),
    specular_strength: Number(clamp(base.specular_strength, 0, 1).toFixed(2)),
  };
}

function compareObjectIds(a, b) {
  return String(a?._id || '').localeCompare(String(b?._id || ''));
}

function selectShadeForVariant(variant, variantIndex, shades, usedShadeIndexes) {
  const normalizedVariantName = normalizeText(variantName(variant));

  // Prefer an unused name match so reordering variants does not silently assign a wrong colour.
  for (let index = 0; index < shades.length; index += 1) {
    if (usedShadeIndexes.has(index)) continue;
    const shadeName = normalizeText(shades[index].name);
    if (shadeName && (normalizedVariantName.includes(shadeName) || shadeName.includes(normalizedVariantName))) {
      usedShadeIndexes.add(index);
      return shades[index];
    }
  }

  // dataproduct_copy.js builds variants and product.shades in the same option order.
  if (shades[variantIndex] && !usedShadeIndexes.has(variantIndex)) {
    usedShadeIndexes.add(variantIndex);
    return shades[variantIndex];
  }

  // A variant may already contain its own colour fields after later migrations.
  const embedded = normalizeShadeEntry({
    name: variant.shadeName || variant.shade_name || variantName(variant),
    hex: variant.colorCode || variant.color_code || variant.shadeHex || variant.shade_hex,
    undertone: variant.undertone,
  }, variantIndex);
  if (embedded) return embedded;

  return null;
}

function isActiveVariant(variant) {
  const status = String(variant.variantStatus || variant.variant_status || variant.status || 'active').toLowerCase();
  const activeFlag = variant.isActive ?? variant.is_active;
  return status !== 'inactive' && status !== 'disabled' && status !== 'deleted' && activeFlag !== false;
}

async function connectMongo() {
  let mongoose;
  try {
    // Load the database dependency only in database mode so --self-test works anywhere.
    mongoose = require('mongoose');
  } catch (error) {
    throw new Error(`Missing runtime dependency: ${error.message}. Run \"npm install dotenv mongoose\" from the backend root.`);
  }

  const uri = process.env.MONGODB_URI || process.env.MONGO_URI || process.env.MONGODB_URL || process.env.DATABASE_URL;
  if (!uri) {
    throw new Error('Missing MongoDB connection string. Set MONGODB_URI or MONGO_URI in .env');
  }

  const options = process.env.MONGODB_DB_NAME ? { dbName: process.env.MONGODB_DB_NAME } : undefined;
  await mongoose.connect(uri, options);
  console.log(`Connected to MongoDB database: ${mongoose.connection.name}`);
  return mongoose;
}

async function collectionExists(db, name) {
  const result = await db.listCollections({ name }, { nameOnly: true }).toArray();
  return result.length > 0;
}

async function safeFindAll(db, collectionName, filter = {}) {
  if (!(await collectionExists(db, collectionName))) return [];
  return db.collection(collectionName).find(filter).toArray();
}

function priceForVariant(variant, product, priceEntriesByVariant) {
  const entries = priceEntriesByVariant.get(String(variant._id)) || [];
  const active = entries.filter((entry) => entry.isActive !== false && entry.is_active !== false);

  if (active.length) {
    const candidates = active
      .map((entry) => Number(entry.salePriceAmount || entry.sale_price_amount || entry.listPriceAmount || entry.list_price_amount || 0))
      .filter((value) => Number.isFinite(value) && value > 0);
    if (candidates.length) return Math.min(...candidates);
  }

  const variantPrice = Number(variant.price || variant.salePriceAmount || variant.sale_price_amount || 0);
  if (variantPrice > 0) return variantPrice;
  return productPrice(product);
}

function inventoryForVariant(variant, product, inventoryByVariant) {
  const balances = inventoryByVariant.get(String(variant._id)) || [];
  if (balances.length) {
    const available = balances.reduce((sum, row) => {
      const quantity = Number(row.availableQty ?? row.available_qty ?? row.onHandQty ?? row.on_hand_qty ?? 0);
      return sum + (Number.isFinite(quantity) ? Math.max(0, quantity) : 0);
    }, 0);
    return { stockQty: available, inStock: available > 0, source: 'inventory_balances' };
  }

  const variantQty = Number(variant.stock ?? variant.availableQty ?? variant.available_qty);
  if (Number.isFinite(variantQty)) {
    return { stockQty: Math.max(0, variantQty), inStock: variantQty > 0, source: 'product_variants' };
  }

  const fallback = productStock(product);
  return { stockQty: fallback, inStock: fallback > 0, source: 'products_fallback' };
}

function mediaForVariant(variant, product, variantMediaByVariant, productMediaByProduct) {
  const variantMedia = (variantMediaByVariant.get(String(variant._id)) || [])
    .filter((media) => media.mediaUrl || media.media_url || media.imageUrl || media.image_url)
    .sort((a, b) => Number(Boolean(b.isPrimary ?? b.is_primary)) - Number(Boolean(a.isPrimary ?? a.is_primary)) || Number(a.sortOrder || a.sort_order || 0) - Number(b.sortOrder || b.sort_order || 0));

  if (variantMedia.length) {
    return variantMedia[0].mediaUrl || variantMedia[0].media_url || variantMedia[0].imageUrl || variantMedia[0].image_url;
  }

  const productMedia = (productMediaByProduct.get(String(product._id)) || [])
    .filter((media) => media.mediaUrl || media.media_url || media.imageUrl || media.image_url)
    .sort((a, b) => Number(Boolean(b.isPrimary ?? b.is_primary)) - Number(Boolean(a.isPrimary ?? a.is_primary)) || Number(a.sortOrder || a.sort_order || 0) - Number(b.sortOrder || b.sort_order || 0));

  if (productMedia.length) {
    return productMedia[0].mediaUrl || productMedia[0].media_url || productMedia[0].imageUrl || productMedia[0].image_url;
  }

  return product.imageUrl || product.image_url || '';
}

function groupBy(items, keyResolver) {
  const map = new Map();
  for (const item of items) {
    const key = keyResolver(item);
    if (!key) continue;
    const stringKey = String(key);
    if (!map.has(stringKey)) map.set(stringKey, []);
    map.get(stringKey).push(item);
  }
  return map;
}

function buildArVariant({ variant, shade, product, arType, finishType, profile, priceEntriesByVariant, inventoryByVariant, variantMediaByVariant, productMediaByProduct, displayOrder }) {
  const inventory = inventoryForVariant(variant, product, inventoryByVariant);
  const price = priceForVariant(variant, product, priceEntriesByVariant);

  return {
    variant_id: variant._id,
    sku: variantSku(variant),
    variant_name: variantName(variant),
    shade_name: shade.name,
    shade_hex: shade.hex,
    undertone: shade.undertone,
    finish_type: finishType,
    opacity: profile.opacity,
    coverage: profile.coverage,
    edge_feather: profile.edge_feather,
    texture_retention: profile.texture_retention,
    saturation: profile.saturation,
    brightness_bias: profile.brightness_bias,
    roughness: profile.roughness,
    specular_strength: profile.specular_strength,
    price,
    currency_code: 'VND',
    stock_qty: inventory.stockQty,
    in_stock: inventory.inStock,
    stock_source: inventory.source,
    thumbnail_url: mediaForVariant(variant, product, variantMediaByVariant, productMediaByProduct),
    calibration_status: 'DRAFT',
    calibrated_hex: null,
    enabled: true,
    display_order: displayOrder,
  };
}

async function resetManagedData(db) {
  if (!RESET) return;

  console.log(`Resetting records managed by ${SEED_BATCH}${DRY_RUN ? ' (dry-run)' : ''}...`);
  if (DRY_RUN) return;

  if (await collectionExists(db, COLLECTION.arConfigs)) {
    const deletedConfigs = await db.collection(COLLECTION.arConfigs).deleteMany({ seed_batch: SEED_BATCH });
    console.log(`  ${COLLECTION.arConfigs}: deleted ${deletedConfigs.deletedCount}`);
  }

  if (await collectionExists(db, COLLECTION.productAttributes)) {
    const deletedAttributes = await db.collection(COLLECTION.productAttributes).deleteMany({ seed_batch: SEED_BATCH });
    console.log(`  ${COLLECTION.productAttributes}: deleted ${deletedAttributes.deletedCount}`);
  }

  await db.collection(COLLECTION.products).updateMany(
    { ar_seed_batch: SEED_BATCH },
    {
      $set: { hasAr: false, updatedAt: new Date() },
      $unset: {
        ar_type: '',
        ar_renderer_version: '',
        ar_config_status: '',
        ar_config_id: '',
        ar_seed_batch: '',
        ar_configured_at: '',
      },
    },
  );
}

async function ensureIndexes(db) {
  if (DRY_RUN) return;

  await db.collection(COLLECTION.arConfigs).createIndex({ product_id: 1 }, { unique: true, name: 'uq_product_ar_configs_product_id' });
  await db.collection(COLLECTION.arConfigs).createIndex({ status: 1, ar_type: 1 }, { name: 'ix_product_ar_configs_status_type' });
  await db.collection(COLLECTION.arConfigs).createIndex({ 'variants.variant_id': 1 }, { name: 'ix_product_ar_configs_variant_id' });
}

async function upsertProductAttributes(db, product, arType, variantCount, now) {
  const attributeRows = [
    ['AR Try-On', 'Có'],
    ['AR Type', arType],
    ['Vùng mô phỏng AR', AR_REGION_LABELS[arType]],
    ['Phiên bản AR Renderer', DEFAULT_RENDERER_VERSION],
    ['Số biến thể AR', String(variantCount)],
  ];

  if (DRY_RUN) return attributeRows.length;

  const ops = attributeRows.map(([attributeName, attributeValue], index) => ({
    updateOne: {
      filter: { productId: product._id, attributeName },
      update: {
        $set: {
          attributeValue,
          displayOrder: 90 + index,
          seed_batch: SEED_BATCH,
          updatedAt: now,
        },
        $setOnInsert: {
          _id: new (require('mongoose').Types.ObjectId)(deterministicObjectIdHex(`attribute:${String(product._id)}:${attributeName}`)),
          productId: product._id,
          attributeName,
          createdAt: now,
        },
      },
      upsert: true,
    },
  }));

  await db.collection(COLLECTION.productAttributes).bulkWrite(ops, { ordered: false });
  return attributeRows.length;
}

async function syncUnsupportedProduct(db, product, now) {
  if (!SYNC_ALL) return;
  if (DRY_RUN) return;

  await db.collection(COLLECTION.products).updateOne(
    { _id: product._id },
    {
      $set: { hasAr: false, updatedAt: now },
      $unset: {
        ar_type: '',
        ar_renderer_version: '',
        ar_config_status: '',
        ar_config_id: '',
        ar_seed_batch: '',
        ar_configured_at: '',
      },
    },
  );

  // Only disable/delete configs created by this script. Do not destroy manually managed configs.
  if (await collectionExists(db, COLLECTION.arConfigs)) {
    await db.collection(COLLECTION.arConfigs).updateOne(
      { product_id: product._id, seed_batch: SEED_BATCH },
      { $set: { status: 'disabled', updatedAt: now } },
    );
  }

  if (await collectionExists(db, COLLECTION.productAttributes)) {
    await db.collection(COLLECTION.productAttributes).deleteMany({
      productId: product._id,
      attributeName: { $in: AR_ATTRIBUTE_NAMES },
      seed_batch: SEED_BATCH,
    });
  }
}

async function sync() {
  const mongoose = await connectMongo();
  const db = mongoose.connection.db;

  try {
    await resetManagedData(db);
    await ensureIndexes(db);

    const productFilter = ONLY_PRODUCT_ID
      ? { _id: new mongoose.Types.ObjectId(ONLY_PRODUCT_ID) }
      : {};

    const [products, categories, variants, variantMedia, productMedia, inventoryBalances, priceBookEntries] = await Promise.all([
      safeFindAll(db, COLLECTION.products, productFilter),
      safeFindAll(db, COLLECTION.categories),
      safeFindAll(db, COLLECTION.variants),
      safeFindAll(db, COLLECTION.variantMedia),
      safeFindAll(db, COLLECTION.productMedia),
      safeFindAll(db, COLLECTION.inventoryBalances),
      safeFindAll(db, COLLECTION.priceBookEntries),
    ]);

    if (!products.length) throw new Error('No products found. Run dataproduct_copy.js before dataAR.js.');
    if (!variants.length) throw new Error('No product_variants found. Run dataproduct_copy.js before dataAR.js.');

    const categoryById = new Map(categories.map((category) => [String(category._id), category]));
    const variantsByProduct = groupBy(variants, variantProductId);
    const variantMediaByVariant = groupBy(variantMedia, (row) => row.variantId || row.variant_id);
    const productMediaByProduct = groupBy(productMedia, (row) => row.productId || row.product_id);
    const inventoryByVariant = groupBy(inventoryBalances, (row) => row.variantId || row.variant_id);
    const priceEntriesByVariant = groupBy(priceBookEntries, (row) => row.variantId || row.variant_id);

    const summary = {
      scannedProducts: 0,
      eligibleProducts: 0,
      skippedUnsupported: 0,
      skippedMissingShade: 0,
      skippedMissingVariant: 0,
      arVariants: 0,
      attributes: 0,
      byType: { LIPS: 0, CHEEKS: 0, EYES: 0 },
      warnings: [],
    };

    for (const product of products.sort((a, b) => productName(a).localeCompare(productName(b)))) {
      summary.scannedProducts += 1;
      const now = new Date();
      const categoryId = normalizeId(product.categoryId || product.category_id || product.category);
      const category = categoryById.get(String(categoryId)) || {
        categoryCode: product.categoryCode || product.category_code,
        categoryName: product.categoryName || product.category_name,
      };
      const arType = inferArType(category);

      if (!arType) {
        summary.skippedUnsupported += 1;
        await syncUnsupportedProduct(db, product, now);
        continue;
      }

      const shades = productShades(product);
      if (!shades.length) {
        summary.skippedMissingShade += 1;
        summary.warnings.push(`${productName(product)}: supported category ${arType} but no valid product.shades[].hex`);
        await syncUnsupportedProduct(db, product, now);
        continue;
      }

      const productVariants = (variantsByProduct.get(String(product._id)) || [])
        .filter(isActiveVariant)
        .sort(compareObjectIds);

      if (!productVariants.length) {
        summary.skippedMissingVariant += 1;
        summary.warnings.push(`${productName(product)}: no active product_variants`);
        await syncUnsupportedProduct(db, product, now);
        continue;
      }

      const finishType = mapFinishType({
        ...product,
        finish: product.finish_type || product.finish,
        categoryCode: category.categoryCode || category.category_code,
      }, arType);
      const profile = renderProfile(product, arType, finishType);
      const usedShadeIndexes = new Set();
      const arVariants = [];

      productVariants.forEach((variant, index) => {
        const shade = selectShadeForVariant(variant, index, shades, usedShadeIndexes);
        if (!shade) {
          summary.warnings.push(`${productName(product)} / ${variantName(variant)}: no valid shade mapping; variant skipped`);
          return;
        }

        arVariants.push(buildArVariant({
          variant,
          shade,
          product,
          arType,
          finishType,
          profile,
          priceEntriesByVariant,
          inventoryByVariant,
          variantMediaByVariant,
          productMediaByProduct,
          displayOrder: arVariants.length + 1,
        }));
      });

      if (!arVariants.length) {
        summary.skippedMissingShade += 1;
        summary.warnings.push(`${productName(product)}: zero AR variants after shade mapping`);
        await syncUnsupportedProduct(db, product, now);
        continue;
      }

      const defaultVariant = arVariants.find((row) => row.in_stock) || arVariants[0];
      const configDocument = {
        product_id: product._id,
        product_name_snapshot: productName(product),
        category_code_snapshot: category.categoryCode || category.category_code || '',
        status: 'active',
        ar_type: arType,
        renderer_version: DEFAULT_RENDERER_VERSION,
        mesh_texture_key: arType === 'LIPS' ? 'lips_v2' : arType === 'CHEEKS' ? 'cheeks_v2' : 'eyes_v2',
        default_variant_id: defaultVariant.variant_id,
        variant_count: arVariants.length,
        variants: arVariants,
        disclaimer: DISCLAIMER,
        source: 'catalog_sync',
        seed_batch: SEED_BATCH,
        updatedAt: now,
      };

      console.log(`${DRY_RUN ? '[DRY-RUN] ' : ''}${arType.padEnd(6)} | ${productName(product)} | ${arVariants.length} variants | ${finishType}`);

      if (!DRY_RUN) {
        const configResult = await db.collection(COLLECTION.arConfigs).findOneAndUpdate(
          { product_id: product._id },
          {
            $set: configDocument,
            $setOnInsert: {
              _id: new mongoose.Types.ObjectId(deterministicObjectIdHex(`config:${String(product._id)}`)),
              createdAt: now,
            },
          },
          { upsert: true, returnDocument: 'after' },
        );

        const config = configResult?.value || configResult;
        await db.collection(COLLECTION.products).updateOne(
          { _id: product._id },
          {
            $set: {
              hasAr: true,
              ar_type: arType,
              ar_renderer_version: DEFAULT_RENDERER_VERSION,
              ar_config_status: 'active',
              ar_config_id: config?._id || new mongoose.Types.ObjectId(deterministicObjectIdHex(`config:${String(product._id)}`)),
              ar_seed_batch: SEED_BATCH,
              ar_configured_at: now,
              updatedAt: now,
            },
          },
        );
      }

      summary.attributes += await upsertProductAttributes(db, product, arType, arVariants.length, now);
      summary.eligibleProducts += 1;
      summary.arVariants += arVariants.length;
      summary.byType[arType] += 1;
    }

    console.log('\nAR seed summary');
    console.log(JSON.stringify(summary, null, 2));

    if (summary.warnings.length) {
      console.warn('\nWarnings:');
      summary.warnings.forEach((warning) => console.warn(`- ${warning}`));
    }

    console.log(`\n${DRY_RUN ? 'Dry-run complete. No database writes were made.' : 'AR catalog synchronization completed successfully.'}`);
  } finally {
    await mongoose.disconnect();
  }
}

function runSelfTest() {
  const assert = require('assert');

  assert.strictEqual(normalizeHex('#e0115f'), '#E0115F');
  assert.strictEqual(normalizeHex('F88379'), '#F88379');
  assert.strictEqual(normalizeHex('#ZZZZZZ'), null);

  assert.strictEqual(inferArType({ categoryCode: 'CAT_LIPSTICK' }), 'LIPS');
  assert.strictEqual(inferArType({ categoryCode: 'CAT_BLUSH' }), 'CHEEKS');
  assert.strictEqual(inferArType({ categoryCode: 'CAT_EYESHADOW' }), 'EYES');
  assert.strictEqual(inferArType({ categoryCode: 'CAT_FOUNDATION' }), null);
  assert.strictEqual(inferArType({ categoryCode: 'CAT_MASCARA' }), null);
  assert.strictEqual(inferArType({ categoryName: 'Má hồng' }), 'CHEEKS');

  assert.strictEqual(mapFinishType({ finish: 'velvet', categoryCode: 'CAT_LIP_TINT' }, 'LIPS'), 'MATTE');
  assert.strictEqual(mapFinishType({ finish: 'glossy', categoryCode: 'CAT_LIP_TINT' }, 'LIPS'), 'GLOSSY');
  assert.strictEqual(mapFinishType({ finish: 'natural', categoryCode: 'CAT_BLUSH' }, 'CHEEKS'), 'SATIN');

  const matteProfile = renderProfile({ coverage: 'full' }, 'LIPS', 'MATTE');
  assert(matteProfile.opacity > BASE_RENDER_PROFILES.LIPS.MATTE.opacity);
  assert(matteProfile.texture_retention > 0);

  const shades = productShades({
    shades: [
      { name: 'Ruby Red', hex: '#E0115F', undertone: 'cool' },
      { shade_name: 'Coral Pink', shade_hex: '#F88379', undertone: 'warm' },
    ],
  });
  assert.strictEqual(shades.length, 2);
  assert.strictEqual(shades[1].hex, '#F88379');

  console.log('dataAR.js self-test: PASS');
}

if (SELF_TEST) {
  runSelfTest();
} else {
  sync().catch((error) => {
    console.error('dataAR.js failed:', error.stack || error.message || error);
    process.exitCode = 1;
  });
}
